### ISSUE TITLE
Export config volume

### ISSUE THREAD

**Issue by PlusMinus0** [QuantumObject/docker-ampache#1]
Hey, could you export the config (and maybe even the themes) folder like the official ampache container is doing?

    VOLUME ["/var/www/config"]
    VOLUME ["/var/www/themes"]

Thanks you for the container, it looks much cleaner than the official one.

**Comment by angelrr7702** [comment]
Sorry , At this moment ... docker build at https://hub.docker.com  it failing for all my container (before I didn't have this problem) ... no idea the reason .. but maybe they change the rules again , when this is change or I have better knowledge what is going on and what need to do for my container to be able to build .. i will have to wait .. for change back the way it was before or wait I will be able to change all my container for the new way of docker to build work without failure  .. or combination of both .. I will update when done with it .

**Comment by angelrr7702** [comment]
Yes, There appear that docker.com have some problem with site:  https://hub.docker.com/

https://github.com/docker/hub-feedback/issues/466

https://github.com/docker/hub-feedback/issues/465

**Comment by PlusMinus0** [comment]
Thanks, I'll be patient :+1:

**Comment by angelrr7702** [comment]
done. please let me know if working .. I send to docker hub request to build it.

**Comment by PlusMinus0** [comment]
Didn't work. I think the reason is that in your container, the ampache configuration is in another subdirectory, right? So it should be /var/www/ampache/conf .

**Comment by angelrr7702** [comment]
fix but need to wait for container finish building at docker hub
