### ISSUE TITLE
Re-install after docker restart

### ISSUE THREAD

**Issue by gmarjano** [QuantumObject/docker-ampache#3]
Hi,

I got a problem with the docker-ampache. I installed it, like it is described on your github site. I enter the browser and the installation process is processed. 

Ampache is working fine until I restart the docker-container (e.g. simulating a reboot of the server).

After I restart the docker-container with the same command
`$ docker run -d -p xxxx:80 -v /src/data:/var/data --link some-mysql:db quantumobject/docker-ampache``

The install process occurs again...

**Comment by angelrr7702** [comment]
docker run ==> that start a new container ..

To restart container is 

docker restart conrainer_ID

or 

docker stop container_id
docker start  container_id

-v /src/data:/var/data  this to keep data (in this case music,etc) , but don't to keep the complete application.

after you reboot the server only you need to run docker start container-ID (the container already produce before by docker run)

sincerely
Angel Rodriguez
